package de.Maxr1998.modernpreferences.preferences.choice

import android.content.Context
import de.Maxr1998.modernpreferences.helpers.DISABLED_RESOURCE_ID

class MultiIntChoiceDialogPreference(
    key: String,
    items: List<SelectionItem<Int>>,
) : AbstractChoiceDialogPreference<Int>(key, items, true) {

    /**
     * The initial selections if no choice has been made yet and no value
     * was persisted to [SharedPreferences][android.content.SharedPreferences]
     */
    var initialSelections: Int = 0

    private var selections: Int = 0

    val currentSelections: Set<SelectionItem<String>>
        get() = HashSet(selections)

    var selectionChangeListener: OnSelectionChangeListener? = null

    override fun onAttach() {
        super.onAttach()
        if (selections == 0) {
            resetSelection()
        }
    }

    override fun select(item: SelectionItem<Int>) {
        if (item.key and selections == 0) {
            selections = selections or item.key
        } else {
            selections = selections and item.key.inv()
        }
        selectionAdapter?.notifySelectionChanged()
    }

    override fun isSelected(item: SelectionItem<Int>): Boolean {
        return item.key and selections != 0
    }

    override fun persistSelection() {
        if (selectionChangeListener?.onSelectionChange(this, selections) != false) {
            commitInt(selections)
        }
    }

    override fun resetSelection() {
        selections = getInt(initialSelections)
        selectionAdapter?.notifySelectionChanged()
    }

    override fun resolveSummary(context: Context): CharSequence? = when {
        autoGeneratedSummary && selections != 0 -> {
            items.filter {
                isSelected(it)
            }.joinToString(limit = 3, truncated = "…") { selection ->
                when {
                    selection.titleRes != DISABLED_RESOURCE_ID -> context.resources.getText(selection.titleRes)
                    else -> selection.title
                }
            }
        }
        else -> super.resolveSummary(context)
    }

    fun interface OnSelectionChangeListener {
        /**
         * Notified when the selection of the connected [MultiChoiceDialogPreference] changes,
         * meaning after the user closes the dialog by pressing "ok".
         * This is called before the change gets persisted and can be prevented by returning false.
         *
         * @param selection the new selection
         *
         * @return true to commit the new selection to [SharedPreferences][android.content.SharedPreferences]
         */
        fun onSelectionChange(preference: MultiIntChoiceDialogPreference, selection: Int): Boolean
    }
}